Add backwards compability for Rails < 5.0
dankimio/tinkoff pull request #5
Opened 2022-04-29 19:15 UTC by sadfuzzy

Add backward compability for Rails < 5.0.
ActiveSupport dependency removed. Replaced single `present?` method with `to_s.empty?`

2022-04-30 20:41 UTC, dankimio requested changes
Thank you! Could you please remove changes with `# frozen_string_literal: true`? I might add these later separately.

2022-07-08 15:52 UTC, sadfuzzy commented
done)

2022-07-08 15:57 UTC, dankimio commented
@sadfuzzy Thanks!

> Replaced single present? method with to_s.empty?

Are we also including this change?

2022-07-11 06:04 UTC, sadfuzzy commented
done)

2022-07-11 06:06 UTC, dankimio approved these changes

2022-07-11 06:06 UTC, merged

2022-07-11 06:27 UTC, dankimio commented
Published in [v0.2.0](https://github.com/dankimio/tinkoff/releases/tag/v0.2.0).